using System.Text.Json;using Medzo.CatalogueInventory.Application.Common;using Medzo.CatalogueInventory.Domain.Catalogue;using Medzo.CatalogueInventory.Domain.Inventory;using Medzo.CatalogueInventory.Domain.Messaging;using Microsoft.EntityFrameworkCore;
namespace Medzo.CatalogueInventory.Infrastructure.Persistence;
public sealed class CatalogueInventoryDbContext(DbContextOptions<CatalogueInventoryDbContext> options):DbContext(options),ICatalogueInventoryStore{
 public DbSet<Medicine> MedicineSet=>Set<Medicine>();public DbSet<Category> Categories=>Set<Category>();public DbSet<InventoryItem> InventoryItemSet=>Set<InventoryItem>();public DbSet<StockBatch> StockBatches=>Set<StockBatch>();public DbSet<StockMovement> MovementSet=>Set<StockMovement>();public DbSet<ProcessedEvent> ProcessedEvents=>Set<ProcessedEvent>();public DbSet<OutboxMessage> OutboxMessages=>Set<OutboxMessage>();
 IQueryable<Medicine> ICatalogueInventoryStore.Medicines=>MedicineSet;IQueryable<InventoryItem> ICatalogueInventoryStore.InventoryItems=>InventoryItemSet;IQueryable<StockBatch> ICatalogueInventoryStore.StockBatches=>StockBatches;IQueryable<StockMovement> ICatalogueInventoryStore.StockMovements=>MovementSet;
 protected override void OnModelCreating(ModelBuilder b){b.ApplyConfigurationsFromAssembly(typeof(CatalogueInventoryDbContext).Assembly);foreach(var entity in b.Model.GetEntityTypes().Where(x=>typeof(Medzo.CatalogueInventory.Domain.Common.Entity).IsAssignableFrom(x.ClrType)))b.Entity(entity.ClrType).Property(nameof(Medzo.CatalogueInventory.Domain.Common.Entity.Id)).ValueGeneratedNever();}
 public Task AddMedicineAsync(Medicine x,CancellationToken ct)=>MedicineSet.AddAsync(x,ct).AsTask();public Task AddInventoryItemAsync(InventoryItem x,CancellationToken ct)=>InventoryItemSet.AddAsync(x,ct).AsTask();public Task AddBatchAsync(StockBatch x,CancellationToken ct)=>StockBatches.AddAsync(x,ct).AsTask();
 public async Task<T> ExecuteTransactionAsync<T>(Func<CancellationToken,Task<T>> action,CancellationToken ct){if(Database.CurrentTransaction is not null)return await action(ct);await using var tx=await Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);try{var result=await action(ct);await tx.CommitAsync(ct);return result;}catch{await tx.RollbackAsync(ct);ChangeTracker.Clear();throw;}}
 public async Task<bool> TryBeginEventAsync(Guid eventId,string topic,CancellationToken ct){if(await ProcessedEvents.AnyAsync(x=>x.EventId==eventId,ct))return false;await ProcessedEvents.AddAsync(new(eventId,topic),ct);return true;}
 public void AddOutbox(string topic,string key,string type,object data)=>OutboxMessages.Add(new(topic,key,type,JsonSerializer.Serialize(new{eventId=Guid.NewGuid(),eventType=type,eventVersion=1,occurredAtUtc=DateTime.UtcNow,producer="medzo-catalogue-inventory-service",data})));
}
