using Medzo.CatalogueInventory.Domain.Catalogue;using Medzo.CatalogueInventory.Domain.Inventory;using Medzo.CatalogueInventory.Domain.Messaging;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Medzo.CatalogueInventory.Infrastructure.Persistence;
public sealed class MedicineConfiguration:IEntityTypeConfiguration<Medicine>{public void Configure(EntityTypeBuilder<Medicine>b){b.ToTable("medicines");b.HasKey(x=>x.Id);b.Property(x=>x.Name).HasMaxLength(200).IsRequired();b.Property(x=>x.NormalizedName).HasMaxLength(200).IsRequired();b.HasIndex(x=>x.NormalizedName).IsUnique();b.Property(x=>x.GenericName).HasMaxLength(200).IsRequired();b.Property(x=>x.Manufacturer).HasMaxLength(200).IsRequired();b.Property(x=>x.UnitPrice).HasPrecision(12,2);b.HasOne(x=>x.Category).WithMany(x=>x.Medicines).HasForeignKey(x=>x.CategoryId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.InventoryItem).WithOne().HasForeignKey<InventoryItem>(x=>x.MedicineId);}}
public sealed class CategoryConfiguration:IEntityTypeConfiguration<Category>{public void Configure(EntityTypeBuilder<Category>b){b.ToTable("categories");b.HasKey(x=>x.Id);b.Property(x=>x.Name).HasMaxLength(100).IsRequired();b.HasIndex(x=>x.Name).IsUnique();}}
public sealed class InventoryConfiguration:IEntityTypeConfiguration<InventoryItem>{public void Configure(EntityTypeBuilder<InventoryItem>b){b.ToTable("inventory_items");b.HasKey(x=>x.Id);b.HasIndex(x=>x.MedicineId).IsUnique();b.Property(x=>x.Version);b.Ignore(x=>x.IsLowStock);b.HasMany(x=>x.Batches).WithOne().HasForeignKey(x=>x.InventoryItemId);b.HasMany(x=>x.Movements).WithOne().HasForeignKey(x=>x.InventoryItemId);}}
public sealed class BatchConfiguration:IEntityTypeConfiguration<StockBatch>{public void Configure(EntityTypeBuilder<StockBatch>b){b.ToTable("stock_batches");b.HasKey(x=>x.Id);b.Property(x=>x.BatchNumber).HasMaxLength(StockBatch.MaxBatchNumberLength).IsRequired();b.Property(x=>x.NormalizedBatchNumber).HasMaxLength(StockBatch.MaxBatchNumberLength).IsRequired();b.Property(x=>x.Description).HasMaxLength(StockBatch.MaxDescriptionLength);b.HasIndex(x=>new{x.InventoryItemId,x.NormalizedBatchNumber}).IsUnique();b.HasIndex(x=>x.ExpiryDate);}}
public sealed class MovementConfiguration:IEntityTypeConfiguration<StockMovement>{public void Configure(EntityTypeBuilder<StockMovement>b){b.ToTable("stock_movements");b.HasKey(x=>x.Id);b.Property(x=>x.SourceType).HasMaxLength(50);b.Property(x=>x.SourceId).HasMaxLength(150);b.HasIndex(x=>new{x.InventoryItemId,x.OccurredAtUtc});}}
public sealed class ProcessedConfiguration:IEntityTypeConfiguration<ProcessedEvent>{public void Configure(EntityTypeBuilder<ProcessedEvent>b){b.ToTable("processed_events");b.HasKey(x=>x.Id);b.HasIndex(x=>x.EventId).IsUnique();b.Property(x=>x.Topic).HasMaxLength(200);}}
public sealed class OutboxConfiguration:IEntityTypeConfiguration<OutboxMessage>{public void Configure(EntityTypeBuilder<OutboxMessage>b){b.ToTable("outbox_messages");b.HasKey(x=>x.Id);b.Property(x=>x.Topic).HasMaxLength(200);b.Property(x=>x.Key).HasMaxLength(100);b.Property(x=>x.Type).HasMaxLength(200);b.Property(x=>x.Payload);b.HasIndex(x=>x.ProcessedAtUtc);}}
