<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Medzo.CatalogueInventory.Application/Medzo.CatalogueInventory.Application.csproj" /><ProjectReference Include="../Medzo.CatalogueInventory.Domain/Medzo.CatalogueInventory.Domain.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1"><PrivateAssets>all</PrivateAssets></PackageReference><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" /><PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" /><PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" /><PackageReference Include="Confluent.Kafka" Version="2.12.0" /></ItemGroup></Project>


